site_name: Kinnari's Site
site_author: Kinnari
site_url: https://kinnariyamamatanha.github.io
site_description: Kinnari 的个人网站
repo_url: https://github.com/KinnariyaMamaTanha/kinnariyamamatanha.github.io/
repo_name: Kinnari's Site
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/KinnariyaMamaTanha/" target="_blank" rel="noopener">Kinnari</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
 
  favicon: img/avatar1.png

  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - callouts
  - changelog
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
  - mkdocs-video:
      video_muted: True
      video_controls: True
      mark: "video"
  - search
  - statistics:
      words_per_minute: 200

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      auto_title: true # 显示编程语言名称
      linenums: true # 显示行号
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  - https://fastly.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js


extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.cs
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css

not_in_nav:
  about.md
  changelog.md
  links.md

nav:
  - Home: index.md
  - Notes: notes/index.md
  - Blogs: blogs/index.md
  - Summaries:
    - index: summary/index.md
    - "2024":
      - "一周反思与总结-5": summary/2024/summary-5.md
      - "一周反思与总结-4": summary/2024/summary-4.md
      - "一周反思与总结-3": summary/2024/summary-3.md
      - "一周反思与总结-2": summary/2024/summary-2.md
      - "aiTour第一年总结与反思": summary/2024/aiTour-first-year.md
  - Links: links.md
  - About: about.md

